CREATE TABLE tb_subscription_price_history
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id   BIGINT         NOT NULL,
    user_id           BIGINT         NOT NULL,
    old_value         NUMERIC(10, 2) NOT NULL,
    new_value         NUMERIC(10, 2) NOT NULL,
    change_percentage NUMERIC(8, 2)  NOT NULL,
    is_price_spike    BOOLEAN        NOT NULL DEFAULT FALSE,
    changed_at        TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_subscription_price_history_subscription
        FOREIGN KEY (subscription_id)
            REFERENCES tb_subscriptions (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_subscription_price_history_user
        FOREIGN KEY (user_id)
            REFERENCES tb_users (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_subscription_price_history_subscription_changed_at
    ON tb_subscription_price_history (subscription_id, changed_at DESC);

CREATE INDEX idx_subscription_price_history_user_spike_changed_at
    ON tb_subscription_price_history (user_id, is_price_spike, changed_at DESC);
