server:
  port: 6969
spring:
  application:
    name: ongoing
  profiles:
    active: ${ACTIVE_PROFILE}
  threads:
    virtual:
      enabled: true

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION}